### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by Rahul3105** [gprasadbhat948231/unequaled-cracker-7155#53]
Website is semi-responsive, some components wasn't made responsive properly, forex:- 
![Screenshot 2023-01-13 at 5 14 58 PM](https://user-images.githubusercontent.com/79327383/212320364-88a1715d-344d-4e3f-b566-7048a476e195.png)

**Comment by Rahul3105** [comment]
React default title and favicon icon is there

**Comment by Rahul3105** [comment]
Using signup form for login, even after successful login, navbar still showing option for login, ideally there should be a avatar icon represent the user currently logged in

**Comment by Rahul3105** [comment]
On eyecare section, product images size are different from each different 
![Screenshot 2023-01-13 at 5 26 57 PM](https://user-images.githubusercontent.com/79327383/212321080-79b0ce4d-4c62-43e3-b5e6-d17d03f0cf30.png)

**Comment by Rahul3105** [comment]
Cart api should have been called inside cart component, user experience would have increased
![Screenshot 2023-01-13 at 5 28 40 PM](https://user-images.githubusercontent.com/79327383/212321216-40a6419d-569a-467a-af83-ba14afacb80f.png)

**Comment by Rahul3105** [comment]
On order placed no api is getting called to record the payment, quite sure it was intentional but an api call could have make the entire flow more complete

**Comment by gprasadbhat948231** [comment]
completed the work flow
